import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {canonical,finiteNumber,integer,safeStorage,outcome,sessionButtons,parseDesign,specFor,validateRestore,formatTime} from '../../rm75_app/web/static/workcell/console/state.js';
import {pieceFaces,pushTransform} from '../../rm75_app/web/static/workcell/console/views.js';
const design={schema:'jimu_builder_scene_v1',pieces:[{role:'base',type:'square',locked:true,center:[0,0,0],u:[1,0,0],n:[0,1,0],v:[0,0,1]},
 {role:'wall',type:'square',locked:false,center:[0,.04,0],u:[1,0,0],n:[0,0,-1],v:[0,1,0]}]};
test('canonical requests ignore key order but preserve list order',()=>{assert.equal(canonical({b:2,a:1}),canonical({a:1,b:2}));assert.notEqual(canonical([1,2]),canonical([2,1]));});
for(const value of ['',null,undefined,'NaN',Infinity,'100'])test('invalid numeric input '+String(value),()=>assert.throws(()=>finiteNumber(value,'X',-3,3)));
test('integer does not truncate fractional seeds',()=>assert.throws(()=>integer('1.5','seed',0,20)));
test('storage failure is contained',()=>{const storage=safeStorage(null);assert.equal(storage.get('a'),null);assert.equal(storage.set('a',{}),false);storage.remove('a');});
test('preview is not verified hardware success',()=>{const r=outcome({status:'command_completed_unverified',result:{verification:'preview_only',task_success:null}});assert.equal(r.verified,false);assert.match(r.label,/未执行动作/);});
test('inconsistent succeeded flag is not a green success',()=>{const r=outcome({status:'succeeded',result:{task_success:false}});assert.equal(r.verified,false);assert.match(r.label,/未确认/);assert.notEqual(r.tone,'good');});
test('surrogate success labelled non-physics',()=>{const r=outcome({status:'succeeded',result:{task_success:true,verification:'surrogate_pose'}});assert.match(r.label,/非物理/);assert.equal(r.tone,'neutral');});
test('failed preview not labelled completed',()=>{const r=outcome({status:'failed',result:{verification:'preview_only'}});assert.equal(r.tone,'bad');assert.doesNotMatch(r.label,/预览完成/);});
const active={managed_active:true,status:'running',request:{task:'pusht',mode:'sim',parameters:{run_until_goal:true,simulation_backend:'full_arm_physics'}}};
test('relocate requires acknowledged pause',()=>{assert.equal(sessionButtons(active,{phase:'executing',safe_to_adjust:false},null).relocate,false);assert.equal(sessionButtons(active,{phase:'paused',safe_to_adjust:true},null).relocate,true);});
test('queued command disables subsequent session actions',()=>{const r=sessionButtons(active,{phase:'paused',safe_to_adjust:true},{sequence:1});assert.equal(r.relocate,false);assert.equal(r.resume,false);assert.equal(r.stop,true);});
test('real records do not expose interactive controls',()=>{const a=structuredClone(active);a.request.mode='real';const b=sessionButtons(a,{phase:'paused',safe_to_adjust:true},null);assert.equal(b.relocate,false);});
test('untracked process is not a managed action target',()=>assert.equal(sessionButtons({...active,managed_active:false},{phase:'paused'},null).stop,false));
test('single-object uses original contract',()=>assert.deepEqual(specFor('pickplace',{objects:['bi'],automatic:true},'sim'),{task:'pickplace',mode:'sim',parameters:{object_name:'bi'}}));
test('all task entrypoints reject real mode',()=>{for(const t of ['pickplace','magnetic','pusht'])assert.throws(()=>specFor(t,{},'real'));});
test('design parsing is lossless for original fields',()=>{const d=structuredClone(design);d.extra={keep:'yes'};assert.deepEqual(parseDesign(JSON.stringify(d)),d);});
for(const change of [d=>d.pieces[0].u=[0,0,0],d=>d.pieces[0].locked='true',d=>d.pieces[1].role='base',d=>d.pieces[1].center=[Infinity,0,0],d=>d.pieces[1].v=[0,-1,0]])test('invalid design fails before canvas normalization '+change.toString(),()=>{const d=structuredClone(design);change(d);assert.throws(()=>parseDesign(JSON.stringify(d)));});
test('proof retained in generated request',()=>{const proof={design_digest:'test'};assert.deepEqual(specFor('magnetic',{designText:JSON.stringify(design),proof},'preview').parameters.generation_proof,proof);});
test('restore permits drafts but not tokens/commands',()=>{const x=validateRestore({schema:1,task:'magnetic',drafts:{},jobId:'a'.repeat(32),arm_token:'secret',execute_real:true});assert.equal(x.jobId,'a'.repeat(32));assert.equal(x.arm_token,undefined);assert.equal(x.execute_real,undefined);});
test('restore rejects malformed pending identity',()=>assert.equal(validateRestore({schema:1,task:'pusht',pending:{id:'../etc',kind:'task'}}).pending,null));
test('world canvas transformation round-trips',()=>{const t=pushTransform({width:920,height:420},[.15,.65,-.3,.3]);const p=[.345,-.173];assert.ok(t.world(t.xy(p)).every((v,i)=>Math.abs(v-p[i])<=2*Number.EPSILON));});
test('viewer leaves original piece untouched',()=>{const p=structuredClone(design.pieces[1]),s=canonical(p);assert.equal(pieceFaces(p).length,6);assert.equal(canonical(p),s);});
test('timer label not used as a task deadline',()=>assert.equal(formatTime(305),'5:05'));
test('remote values never go through dynamic HTML or eval',()=>{const text=readFileSync(new URL('../../rm75_app/web/static/workcell/console/app.js',import.meta.url),'utf8');assert.doesNotMatch(text,/innerHTML|eval\(/);assert.doesNotMatch(text,/attempts\s*<\s*180/);assert.match(text,/generation_status|generations\//);});
